---
title: "DATA_643_Discussion_1"
author: "ppadebettu"
date: "Friday, June 10, 2016"
output: html_document
---


<br>
<h3>1. Scenario Design Analysis for toysrus.com</h3>
<b>1. Identify a recommender system web site</b><br><br>
Almost every other year, we shop for bicycles and we check online first for choice of models and price comparison. We used a web site with a recommender system, Toysrus.com
<br><br>
<b>2. Answer the three scenario design questions for this web site</b><br><br>

a -- Who are your target users?<br>
The site's target users are retail customers shopping for both traditional and electronic toys<br>

b -- What are their key goals?<br>
Their key goals are to get parents shop online for most of the toys particularly during holidays and other sale events. More over, Toysrus would like to establish a strong online presence in offering children's toys as online sales in US are increasing every year compared to brick and mortar stores<br>

c -- How can you help them accomplish their goals?<br>
One way to help Toysrus.com is to be able to come up with a great user experience for the customers during their online shopping process. We can help them think about target market and appropriately tailor content to shoppers. The whole purchasing process has to be as quick as possible to retain shopper's interest in buying products. From an user's perspective, we can help them accomplish their goals by giving feedback on their products, recommendations and by periodically adjusting our interests and categories of products in the profile section

<h3>2. Reverse Engineering of the site</h3>
<p>Toysrus is using traditional tacking features like cookies, sessions, previous browisng history & previous purchase history and online data entered like user search words, filtered categories to provide recommendations to it's online customers. It has sections like "Recommended for you", "Customers also liked", "Shoppers like you also liked" which come up dynamically based on the how we interact with the website</p>
<h3>3. Recommendations for improving recommender capabilities</h3>
<p>One way to improve the capabilties of the recommender is to make efficient use of the user entered search words and category filters to recommending relevant products. In one example, I was searching for bicycles for boys in 24 inch height group, but I was getting toy cars, crayons, girls bicycles in the list of recommended products</p> 
<p>Products like bicycles also need accessories particularly safety lights, locks, bottle holders etc, so the recommender system should also use related product segments to display accessrories which can help both sales for the company and safety aspects for the shopper</p>



